"""add installation_date

Revision ID: 351460c74110
Revises: 0001_initial_complete_schema
Create Date: 2026-02-25 13:05:58.330746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351460c74110'
down_revision: Union[str, None] = '0001_initial_complete_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ticket_id'), table_name='ticket_responses')
    op.drop_index(op.f('ix_ticket_responses_ticket_id'), table_name='ticket_responses')
    op.create_index(op.f('ix_ticket_responses_ticket_id'), 'ticket_responses', ['ticket_id'], unique=True)
    op.drop_index(op.f('ticket_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_code'), table_name='tickets')
    op.create_index(op.f('ix_tickets_ticket_code'), 'tickets', ['ticket_code'], unique=True)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_tickets_ticket_code'), table_name='tickets')
    op.create_index(op.f('ix_tickets_ticket_code'), 'tickets', ['ticket_code'], unique=False)
    op.create_index(op.f('ticket_code'), 'tickets', ['ticket_code'], unique=True)
    op.drop_index(op.f('ix_ticket_responses_ticket_id'), table_name='ticket_responses')
    op.create_index(op.f('ix_ticket_responses_ticket_id'), 'ticket_responses', ['ticket_id'], unique=False)
    op.create_index(op.f('ticket_id'), 'ticket_responses', ['ticket_id'], unique=True)
    op.drop_column('equipment', 'installation_date')
    # ### end Alembic commands ###

