"""create machine_hour_readings table

Revision ID: 99def98b71c3
Revises: 6603a4218e02
Create Date: 2026-03-04 15:52:54.548236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99def98b71c3'
down_revision: Union[str, None] = '6603a4218e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_hour_readings',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('equipment_id', sa.String(
                        length=36), nullable=False),
                    sa.Column('reading_hours', sa.Integer(), nullable=False),
                    sa.Column('reading_date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('machine_hour_readings')
    # ### end Alembic commands ###
