"""add last_pm_date to equipment

Revision ID: d36af6f8c24b
Revises: fff43b0477b8
Create Date: 2026-03-06 10:42:42.507416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36af6f8c24b'
down_revision: Union[str, None] = 'fff43b0477b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('repair_alert_override', sa.String(length=20), nullable=True))
    op.add_column('equipment', sa.Column('last_pm_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_equipment_logs_created_by_user_id'), table_name='equipment_logs')
    op.drop_index(op.f('ix_equipment_logs_equipment_type'), table_name='equipment_logs')
    op.drop_index(op.f('ix_equipment_logs_log_type'), table_name='equipment_logs')
    op.create_unique_constraint('uq_equipment_reading_date', 'machine_hour_readings', ['equipment_id', 'reading_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_equipment_reading_date', 'machine_hour_readings', type_='unique')
    op.create_index(op.f('ix_equipment_logs_log_type'), 'equipment_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_equipment_logs_equipment_type'), 'equipment_logs', ['equipment_id', 'log_type'], unique=False)
    op.create_index(op.f('ix_equipment_logs_created_by_user_id'), 'equipment_logs', ['created_by_user_id'], unique=False)
    op.drop_column('equipment', 'last_pm_date')
    op.drop_column('equipment', 'repair_alert_override')
    # ### end Alembic commands ###

