"""phase2_dialysis_engine

Revision ID: f78fd30666a8
Revises: 99def98b71c3
Create Date: 2026-03-05 13:16:03.758281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78fd30666a8'
down_revision: Union[str, None] = '99def98b71c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # op.drop_column('equipment', 'supplier_id')
    op.add_column('equipment_logs', sa.Column(
        'notes', sa.Text(), nullable=True))

    op.drop_column('equipment_logs', 'description')
    op.drop_column('equipment_logs', 'resolved')
    op.drop_column('equipment_logs', 'title')
    op.drop_column('equipment_logs', 'occurred_at')
    op.drop_column('equipment_logs', 'downtime_minutes')
    op.create_unique_constraint('uq_equipment_reading_date', 'machine_hour_readings', [
                                'equipment_id', 'reading_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_equipment_reading_date',
                       'machine_hour_readings', type_='unique')
    op.add_column('equipment_logs', sa.Column('downtime_minutes', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.add_column('equipment_logs', sa.Column(
        'occurred_at', mysql.DATETIME(), nullable=True))
    op.add_column('equipment_logs', sa.Column(
        'title', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('equipment_logs', sa.Column('resolved', mysql.TINYINT(
        display_width=1), autoincrement=False, nullable=False))
    op.add_column('equipment_logs', sa.Column(
        'description', mysql.TEXT(), nullable=True))
    op.create_index(op.f('ix_equipment_logs_occurred_at'),
                    'equipment_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_equipment_logs_log_type'),
                    'equipment_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_equipment_logs_equipment_type'), 'equipment_logs', [
                    'equipment_id', 'log_type'], unique=False)
    op.create_index(op.f('ix_equipment_logs_created_by_user_id'),
                    'equipment_logs', ['created_by_user_id'], unique=False)
    op.drop_column('equipment_logs', 'notes')
    op.add_column('equipment', sa.Column(
        'supplier_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('equipment_ibfk_3'), 'equipment', 'suppliers', [
                          'supplier_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_equipment_supplier_id'),
                    'equipment', ['supplier_id'], unique=False)
    # ### end Alembic commands ###
