"""add lifecycle support

Revision ID: fff43b0477b8
Revises: f78fd30666a8
Create Date: 2026-03-06 08:49:43.926971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff43b0477b8'
down_revision: Union[str, None] = 'f78fd30666a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('lifecycle_type', sa.Enum(
        'hours', 'years', name='lifecycletype'), nullable=False))
    op.add_column('equipment', sa.Column(
        'lifecycle_years', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('equipment', 'lifecycle_years')
    op.drop_column('equipment', 'lifecycle_type')
    # ### end Alembic commands ###
